name: Build VS Code Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18" # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Install vsce CLI
        run: npm install -g @vscode/vsce

      - name: Lint and build
        run: |
          npm run lint --if-present
          npm run build --if-present

      - name: Package VS Code extension
        run: vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: ./*.vsix
